### ISSUE TITLE
unable to run EACCES

### ISSUE THREAD

**Issue by indraraj26** [suryavaddiraju/irctc-api#72]
I tried with sudo as well. 

mac sonoma 14.6

<ref *1> Error: spawnSync /Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/bin/viu EACCES
    at Object.spawnSync (node:internal/child_process:1124:20)
    at spawnSync (node:child_process:876:24)
    at execFileSync (node:child_process:919:15)
    at viu_captcha (file:///Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/lib/index.mjs:17:41)
    at login (file:///Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/lib/index.mjs:157:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IRCTC.starter (file:///Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/lib/index.mjs:784:13)
    at async IRCTC.book (file:///Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/lib/index.mjs:799:9)
    at async book (file:///Users/indra26/Public/playground/irctc-api-book/index.mjs:29:18) {
  errno: -13,
  code: 'EACCES',
  syscall: 'spawnSync /Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/bin/viu',
  path: '/Users/indra26/Public/playground/irctc-api-book/node_modules/irctc-api/bin/viu',
  spawnargs: [ './captcha.png', '-t' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}

**Comment by nagarajpandith** [comment]
same issue here.
mac m1 air.

**Comment by suryavaddiraju** [comment]
Try running 

```
sudo node /Users/indra26/Public/playground/irctc-api-book/index.mjs
```

**Comment by nagarajpandith** [comment]
> Try running
> 
> ```
> sudo node /Users/indra26/Public/playground/irctc-api-book/index.mjs
> ```

As OP already mentioned, we have tried it with sudo.

**Comment by suryavaddiraju** [comment]
okay will update next version with

```
chmod 777 -R /foo/bar/irctc-api/bin/viu
```

**Comment by indraraj26** [comment]
I even tried with chmod 777 but still it does not work.

**Comment by nagarajpandith** [comment]
@indraraj26 I resolved the viu error
1. i had installed viu using homebrew
2. found the location of viu executable using `brew info viu`
3. executable was inside `/opt/homebrew/Cellar/viu/1.5.1` in my case
4. copied the executable file and pasted it inside bin folder of this api

this resolved the viu error. but some other server related issue came up, so i didn't continue further.

if this doesn't resolve the viu error, try pasting the viu executable somewhere else and give the executable's destination as a param for IRCTC class object.

**Comment by suryavaddiraju** [comment]
Thank you @nagarajpandith for your prompt response to the community.

- Try v3.0.5 using `gcloud` in irctc class param for booking without using `viu`

- Check the latest API Reference Documentation 


Regards
Vaddiraju Surya Teja

**Comment by indraraj26** [comment]
Thank you so much for adding gcloud support.
